=== Abraham-475/lenguaje_d_marcassssss/clase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clase">
        <xs:complexType>
        <xs:sequence>
    <xs:element name="estudiante" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
    <xs:element name="nombre" type="xs:boolean"/>
    <xs:element name="edad" type="xs:float"/>
      <xs:element name="Municipio" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Abraham-475/lenguaje_d_marcassssss/clase.xml
<?xml version="1.0" encoding="UTF-8"?>
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="clase.xsd">
    <estudiante>
        <nombre>1</nombre>
        <edad>20</edad>
        <Municipio>isla</Municipio>
    </estudiante>
    <estudiante>
        <nombre>0</nombre>
        <edad>22</edad>
        <Municipio>lepe</Municipio>
    </estudiante>
</clase>
